from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# data
DATA_DIR = PROJECT_ROOT / "data"

RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

HOT100_OUTPUT = RAW_DATA_DIR / "hot-100-current.csv"
HOT100_SONG_OUTPUT = PROCESSED_DATA_DIR / "hot-100-song_current.parquet"
CHECKPOINT_OUTPUT = PROCESSED_DATA_DIR / "checkpoint.parquet"

# filter time period
START_WEEK = "2020-01-01"
END_WEEK = "2026-08-01"
HOT100_LYRICS_OUTPUT_NAME = f"hot-100-lyrics_{START_WEEK}_{END_WEEK}.parquet"
HOT100_LYRICS_OUTPUT = PROCESSED_DATA_DIR / HOT100_LYRICS_OUTPUT_NAME
HOT100_CHUNKS_OUTPUT_NAME = f"hot-100-chunks_{START_WEEK}_{END_WEEK}.json"
HOT100_CHUNKS_OUTPUT = PROCESSED_DATA_DIR / HOT100_CHUNKS_OUTPUT_NAME
EMBEDDINGS_OUTPUT_NAME = f"embeddings_{START_WEEK}_{END_WEEK}.npy"
EMBEDDINGS_OUTPUT = PROCESSED_DATA_DIR / EMBEDDINGS_OUTPUT_NAME

# search_lyrics.py
CHECKPOINT_EVERY = 100
MAX_RETRIES = 5

# chunk_lyrics.py
MIN_LINES_PER_CHUNK = 4
DEFAULT_LINES_PER_CHUNK = int(1.5 * MIN_LINES_PER_CHUNK)
MAX_LINES_PER_CHUNK = 4 * MIN_LINES_PER_CHUNK

# model
MODEL_DIR = PROJECT_ROOT / "models"

MODEL_NAME = "Xenova/all-MiniLM-L6-v2"
MODEL_PATH = MODEL_DIR / MODEL_NAME

# embedding
BATCH_SIZE = 50
EMBEDDING_DIM = 384  # change with model

# postgres
POSTGRES_USER = "lyricslens"
POSTGRES_PASSWORD = "pswd"
POSTGRES_DB = "lyricslensDB"
HOST = "localhost"
HOST_PORT = "5432"

# search_pgvector.py
TOP_K_SONGS = 5
TOP_K_SECTIONS = 4 * TOP_K_SONGS
